# Generated by Django 4.1.13 on 2024-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
